import styles from "../styles/Home/Home.module.css";
import Head from "next/head";
import { Hero } from "./components/Hero/Hero.jsx";

const Home = () => {
  return (
    <>
      <Head>
        <title>How we work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
    </>
  );
};

export default Home;
